export enum Tones {
    C_Am = "C / Am",
    Cx_Bbm = "C# / Bbm",
    D_Bm = "D / Bm",
    Dx_Cm = "D# / Cm",
    Eb_Dbm = "Eb / Dbm",
    E_Cxm = "E / C#m",
    F_Dm = "F / Dm",
    Fx_Dxm = "F# / D#m",
    G_Em = "G / Em",
    Gx_Fm = "G# / Fm",
    A_Fxm = "A / F#m",
    Ax_Fxm = "A# / Gm",
    Bb_Fxm = "Bb / Abm",
    B_Gxm = "B / G#m",
}